### ISSUE TITLE
Cambiar return string de métodos de las clases

### ISSUE THREAD

**Issue by JosueTC94** [ULL-ESIT-GRADOII-DSI/eliminacion-del-switch-smell-josue-nayra-dsi15-16-1#2]
En todas las temperaturas, clases de distancia y de volumen hay que cambiar el formato en el que se devuelve el resultado, de forma que en lugar de un string se devuelva un objeto.

@alu0100406122

**Comment by alu0100406122** [comment]
Modificados los métodos de todas las clases temperaturas, los cuales devuelven un objeto en vez de un string.

Commit: 9583922c412704ef53d032172b3b7053202ed6ce
